# Generated by Django 3.1.2 on 2022-05-12 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Food')),
                ('description', models.TextField(blank=True, null=True)),
                ('veg_type', models.CharField(choices=[('LF', 'Leafy Green'), ('CF', 'Cruciferous'), ('MW', 'Marrow'), ('RT', 'Root'), ('AL', 'Allium')], default='LF', max_length=50)),
                ('compost', models.CharField(max_length=100)),
                ('harvest', models.CharField(max_length=100)),
                ('watering', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
