# Generated by Django 3.1.2 on 2022-06-15 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20220517_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='veg_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.vegetabletype'),
        ),
        migrations.AlterField(
            model_name='vegetabletype',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
