# Generated by Django 3.1.2 on 2022-06-15 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20220615_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='veg_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.vegetabletype'),
        ),
        migrations.AlterField(
            model_name='vegetabletype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
